#!/usr/bin/env bun

import { REVIEW_HOST_EVIDENCE_POLICY } from "../lib/review-runtime-contract";
import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import {
	copyFileSync,
	cpSync,
	chmodSync,
	existsSync,
	lstatSync,
	mkdirSync,
	readFileSync,
	renameSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { AUTO_ALLOWED_BROWSER_SESSION_COMMANDS } from "../lib/browser-runtime-contract";
import { writeDistributionManifest } from "../../scripts/lib/workflow-distribution-contract.mjs";

const REVIEW_ASSETS = [
	"shared-rubric.md",
	"findings-schema.md",
	"checklist.md",
	"evidence-omission.md",
	"design-checklist.md",
	"greptile-triage.md",
	"TODOS-format.md",
] as const;

const REVIEW_AUTHORING_ASSETS = [
	{ source: "../docs/review-evidence-manifest.md", target: "review/review-evidence-manifest.md" },
	{ source: "../examples/review-evidence/minimal-local-gate.json", target: "review/examples/minimal-local-gate.json" },
	{ source: "../schemas/review-evidence-manifest.schema.json", target: "review/schemas/review-evidence-manifest.schema.json" },
	{ source: "../schemas/review-behavior-matrix.schema.json", target: "review/schemas/review-behavior-matrix.schema.json" },
] as const;

export interface CodexReviewLauncherInstallOptions {
	sourceRoot: string;
	runtimeRoot: string;
	ruleFile: string;
	markerFile: string;
	bunPath: string;
	codexPath: string;
	browserPath: string;
	bundleBrowserServer?: (
		bunPath: string,
		entryFile: string,
		outputDirectory: string,
	) => void;
	afterRuntimeBackup?: () => void;
}

export interface CodexReviewLauncherMarker {
	schemaVersion: 1;
	argvPrefix: [string, string];
	ruleFile: string;
	runtimeRoot: string;
}

function pathIsWithin(parent: string, candidate: string): boolean {
	const child = relative(resolve(parent), resolve(candidate));
	return child === "" || (!child.startsWith(`..${sep}`) && child !== "..");
}

function requireAbsolute(label: string, value: string): string {
	if (!isAbsolute(value)) {
		throw new Error(`${label} must be an absolute path: ${value}`);
	}
	return resolve(value);
}

function starlarkString(value: string): string {
	return JSON.stringify(value);
}

export function renderCodexReviewRule(marker: CodexReviewLauncherMarker): string {
	const [bunPath, launcherPath] = marker.argvPrefix;
	const reviewPattern = [
		bunPath,
		launcherPath,
		"review",
		"code",
		"--host",
		"codex",
	]
		.map(starlarkString)
		.join(", ");
	const browserRules = AUTO_ALLOWED_BROWSER_SESSION_COMMANDS.flatMap(
		(command) => {
			const pattern = [
				bunPath,
				launcherPath,
				"browser",
				"session",
				"--host",
				"codex",
				command,
			]
				.map(starlarkString)
				.join(", ");
			return [
				"prefix_rule(",
				`    pattern = [${pattern}],`,
				'    decision = "allow",',
				`    justification = "Inspect the Goldband-owned browser with ${command} without an approval prompt",`,
				")",
				"",
			];
		},
	);
	return [
		"# Generated by Goldband. Re-run the Codex workflow installer to refresh.",
		"# The launcher is a materialized snapshot outside the active workspace.",
		"prefix_rule(",
		`    pattern = [${reviewPattern}],`,
		'    decision = "allow",',
		'    justification = "Run Goldband-owned read-only typed code review without an approval prompt",',
		")",
		"",
		...browserRules,
	].join("\n");
}

function recoverInterruptedRuntimeSwap(
	runtimeRoot: string,
	backupRoot: string,
): void {
	if (!existsSync(backupRoot)) return;
	if (!existsSync(runtimeRoot)) {
		renameSync(backupRoot, runtimeRoot);
		return;
	}
	rmSync(backupRoot, { recursive: true, force: true });
}

function bundle(
	bunPath: string,
	entryFile: string,
	outputFile: string,
): void {
	mkdirSync(dirname(outputFile), { recursive: true });
	const result = spawnSync(
		bunPath,
		["build", entryFile, "--target=bun", "--outfile", outputFile],
		{ encoding: "utf8" },
	);
	if (result.error) throw result.error;
	if (result.status !== 0) {
		throw new Error(
			`failed to bundle ${entryFile}: ${(result.stderr || result.stdout).trim()}`,
		);
	}
}

function bundleBrowserServer(
	bunPath: string,
	entryFile: string,
	outputDirectory: string,
): void {
	mkdirSync(outputDirectory, { recursive: true });
	const result = spawnSync(
		bunPath,
		[
			"build",
			"--target=bun",
			"--external",
			"electron",
			entryFile,
			"--outdir",
			outputDirectory,
		],
		{ encoding: "utf8" },
	);
	if (result.error) throw result.error;
	if (result.status !== 0) {
		throw new Error(
			`failed to bundle ${entryFile}: ${(result.stderr || result.stdout).trim()}`,
		);
	}
	if (!existsSync(join(outputDirectory, "server.js"))) {
		throw new Error(`browser server bundle is missing server.js: ${outputDirectory}`);
	}
}

function assertRequiredSources(paths: string[]): void {
	for (const path of paths) {
		if (!existsSync(path)) throw new Error(`required source missing: ${path}`);
	}
}

function copyReviewAuthoringAssets(sourceRoot: string, stageRoot: string): void {
	for (const asset of REVIEW_AUTHORING_ASSETS) {
		const source = join(sourceRoot, asset.source);
		const target = join(stageRoot, asset.target);
		mkdirSync(dirname(target), { recursive: true });
		copyFileSync(source, target);
	}
}

export function installCodexReviewLauncher(
	options: CodexReviewLauncherInstallOptions,
): CodexReviewLauncherMarker {
	const sourceRoot = requireAbsolute("sourceRoot", options.sourceRoot);
	const runtimeRoot = requireAbsolute("runtimeRoot", options.runtimeRoot);
	const ruleFile = requireAbsolute("ruleFile", options.ruleFile);
	const markerFile = requireAbsolute("markerFile", options.markerFile);
	const bunPath = requireAbsolute("bunPath", options.bunPath);
	const codexPath = requireAbsolute("codexPath", options.codexPath);
	const browserPath = requireAbsolute("browserPath", options.browserPath);
	const reviewReceiptKeyFile = join(dirname(runtimeRoot), "review-receipt.key");
	const marker: CodexReviewLauncherMarker = {
		schemaVersion: 1,
		argvPrefix: [bunPath, join(runtimeRoot, "bin", "goldband.js")],
		ruleFile,
		runtimeRoot,
	};
	const ruleContents = renderCodexReviewRule(marker);
	const markerContents = `${JSON.stringify(marker, null, 2)}\n`;

	if (pathIsWithin(sourceRoot, runtimeRoot)) {
		throw new Error(
			"trusted review runtime must be outside the Goldband source workspace",
		);
	}
	if (pathIsWithin(sourceRoot, ruleFile) || pathIsWithin(sourceRoot, markerFile)) {
		throw new Error(
			"trusted review rule and marker must be outside the Goldband source workspace",
		);
	}
	if (!existsSync(bunPath)) throw new Error(`bun executable not found: ${bunPath}`);
	if (!existsSync(codexPath))
		throw new Error(`codex executable not found: ${codexPath}`);
	if (!existsSync(browserPath))
		throw new Error(`browser executable not found: ${browserPath}`);

	const launcherEntry = join(sourceRoot, "bin", "goldband.ts");
	const runtimeEntry = join(sourceRoot, "workflows", "run.ts");
	const browserServerEntry = join(sourceRoot, "browse", "src", "server.ts");
	const rulesResolverSource = join(
		sourceRoot,
		"..",
		"hooks",
		"scripts",
		"lib",
		"rules-resolver.js",
	);
	const rulesSource = join(sourceRoot, "..", "rules");
	assertRequiredSources([
		launcherEntry,
		runtimeEntry,
		join(sourceRoot, "workflows", "review-contract-cli.ts"),
		browserServerEntry,
		rulesResolverSource,
		join(rulesSource, "manifest.json"),
		...REVIEW_AUTHORING_ASSETS.map((asset) => join(sourceRoot, asset.source)),
	]);

	const stageRoot = `${runtimeRoot}.tmp-${process.pid}`;
	const backupRoot = `${runtimeRoot}.backup`;
	mkdirSync(dirname(runtimeRoot), { recursive: true });
	ensureReviewReceiptAuthorityKey(reviewReceiptKeyFile);
	recoverInterruptedRuntimeSwap(runtimeRoot, backupRoot);
	rmSync(stageRoot, { recursive: true, force: true });
	try {
		bundle(bunPath, launcherEntry, join(stageRoot, "bin", "goldband.js"));
		bundle(bunPath, runtimeEntry, join(stageRoot, "workflows", "run.ts"));
		bundle(
			bunPath,
			join(sourceRoot, "workflows", "review-contract-cli.ts"),
			join(stageRoot, "workflows", "review-contract-cli.ts"),
		);
		const stagedBrowserExecutable = join(stageRoot, "browse", "browse");
		mkdirSync(dirname(stagedBrowserExecutable), { recursive: true });
		copyFileSync(browserPath, stagedBrowserExecutable);
		chmodSync(stagedBrowserExecutable, 0o700);
		const stagedBrowserServerDirectory = join(stageRoot, "browse", "server");
		(options.bundleBrowserServer ?? bundleBrowserServer)(
			bunPath,
			browserServerEntry,
			stagedBrowserServerDirectory,
		);
		mkdirSync(join(stageRoot, "review"), { recursive: true });
		for (const asset of REVIEW_ASSETS) {
			const source = join(sourceRoot, "review", asset);
			if (!existsSync(source)) throw new Error(`review asset missing: ${source}`);
			copyFileSync(source, join(stageRoot, "review", asset));
		}
		copyReviewAuthoringAssets(sourceRoot, stageRoot);
		const stagedRulesResolver = join(
			stageRoot,
			"review",
			"rules-resolver.js",
		);
		const stagedRulesDirectory = join(stageRoot, "review", "rules");
		copyFileSync(rulesResolverSource, stagedRulesResolver);
		cpSync(rulesSource, stagedRulesDirectory, { recursive: true });
		writeFileSync(
			join(stageRoot, "trusted-runtime.json"),
			`${JSON.stringify(
				{
					schemaVersion: 2,
					runtimeHost: "codex",
					...REVIEW_HOST_EVIDENCE_POLICY,
					codexExecutable: codexPath,
					browserExecutable: join(runtimeRoot, "browse", "browse"),
					browserServerScript: join(
						runtimeRoot,
						"browse",
						"server",
						"server.js",
					),
					bunExecutable: bunPath,
					rulesResolverScript: join(
						runtimeRoot,
						"review",
						"rules-resolver.js",
					),
					rulesDirectory: join(runtimeRoot, "review", "rules"),
					reviewReceiptKeyFile,
					reviewReceiptAuthorityRoot: dirname(runtimeRoot),
					reviewReceiptStore: join(dirname(runtimeRoot), "review-receipts"),
				},
				null,
				2,
			)}\n`,
			{ mode: 0o600 },
		);
		writeDistributionManifest(stageRoot, sourceRoot, [
			{ role: "codex-execpolicy-rule", path: ruleFile, contents: ruleContents, mode: 0o600 },
			{ role: "workflow-launcher-marker", path: markerFile, contents: markerContents, mode: 0o600 },
		]);

		if (existsSync(runtimeRoot)) renameSync(runtimeRoot, backupRoot);
		options.afterRuntimeBackup?.();
		renameSync(stageRoot, runtimeRoot);
		rmSync(backupRoot, { recursive: true, force: true });
	} catch (error) {
		rmSync(stageRoot, { recursive: true, force: true });
		if (!existsSync(runtimeRoot) && existsSync(backupRoot)) {
			renameSync(backupRoot, runtimeRoot);
		}
		throw error;
	}

	for (const [destination, contents] of [
		[ruleFile, ruleContents],
		[markerFile, markerContents],
	] as const) {
		mkdirSync(dirname(destination), { recursive: true });
		const temporary = `${destination}.tmp-${process.pid}`;
		writeFileSync(temporary, contents, { mode: 0o600 });
		renameSync(temporary, destination);
	}

	return marker;
}

function ensureReviewReceiptAuthorityKey(file: string): void {
	if (!existsSync(file)) {
		writeFileSync(file, `${randomBytes(32).toString("hex")}\n`, {
			mode: 0o600,
			flag: "wx",
		});
		return;
	}
	const stat = lstatSync(file);
	if (!stat.isFile() || stat.isSymbolicLink() || (stat.mode & 0o077) !== 0) {
		throw new Error(`review receipt authority key has unsafe permissions: ${file}`);
	}
	if (typeof process.getuid === "function" && stat.uid !== process.getuid()) {
		throw new Error(`review receipt authority key has the wrong owner: ${file}`);
	}
	const value = readFileSync(file, "utf8").trim();
	if (!/^[a-f0-9]{64}$/.test(value)) {
		throw new Error(`review receipt authority key is invalid: ${file}`);
	}
}

function parseArgs(args: string[]): CodexReviewLauncherInstallOptions {
	const values = new Map<string, string>();
	for (let index = 0; index < args.length; index += 2) {
		const key = args[index];
		const value = args[index + 1];
		if (!key?.startsWith("--") || !value) {
			throw new Error(
				"usage: install-codex-review-launcher.ts --source-root <path> --runtime-root <path> --rule-file <path> --marker-file <path> --bun-path <path> --codex-path <path> --browser-path <path>",
			);
		}
		values.set(key, value);
	}
	const read = (key: string): string => {
		const value = values.get(key);
		if (!value) throw new Error(`missing required option: ${key}`);
		return value;
	};
	return {
		sourceRoot: read("--source-root"),
		runtimeRoot: read("--runtime-root"),
		ruleFile: read("--rule-file"),
		markerFile: read("--marker-file"),
		bunPath: read("--bun-path"),
		codexPath: read("--codex-path"),
		browserPath: read("--browser-path"),
	};
}

if (import.meta.main) {
	try {
		const marker = installCodexReviewLauncher(parseArgs(process.argv.slice(2)));
		console.log(`  trusted workflow launcher: ${marker.argvPrefix.join(" ")}`);
		console.log(`  trusted workflow rule: ${marker.ruleFile}`);
	} catch (error) {
		console.error(
			`goldband setup failed: ${error instanceof Error ? error.message : String(error)}`,
		);
		process.exit(1);
	}
}
